### ISSUE TITLE
AozoraEpub3 is not modified

### ISSUE THREAD

**Issue by jam7** [migimigi/narou-docker#1]
こんにちは、narou-dockerありがとうございます。

Dockerfileなどを見ていると、初回の`docker run`中に`narou init`を実行して`/opt/AozoraEpub3/chuki_tag.txt`を書き換えているのですが、`/opt/AozoraEpub3`はコンテナの中なので、2回目以降の`docker run`では、ホスト側の`.narou`ディレクトリは残っているのですが、`/opt/AozoraEpub3`の変更が元に戻ってしまっています。

もしよければ修正してもらえませんでしょうか。

**Comment by migimigi** [comment]
issueに全く気が付かずにすいません。
とりあえずDockerfile中で、narou initで行ってる処理相当の書き換えを行ってみました。
77fa21f

**Comment by jam7** [comment]
対応ありがとうございました。
